/* Autogenerated by /usr/bin/halcompile on Tue Sep  7 18:25:38 2021 -- do not edit */
#include "rtapi.h"
#ifdef RTAPI
#include "rtapi_app.h"
#endif
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"
#include "rtapi_math64.h"

static int comp_id;

#ifdef MODULE_INFO
MODULE_INFO(linuxcnc, "component:syncoutputv1:");
MODULE_INFO(linuxcnc, "pin:output:bit:0:out::None:None");
MODULE_INFO(linuxcnc, "pin:x_target:float:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:y_target:float:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:x_current:float:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:y_current:float:0:in::None:None");
MODULE_INFO(linuxcnc, "param:delta:float:0:r::0.01:None");
MODULE_INFO(linuxcnc, "funct:_:1:");
MODULE_INFO(linuxcnc, "license:smandyscom");
MODULE_LICENSE("smandyscom");
#endif // MODULE_INFO


struct __comp_state {
    struct __comp_state *_next;
    hal_bit_t *output;
    hal_float_t *x_target;
    hal_float_t *y_target;
    hal_float_t *x_current;
    hal_float_t *y_current;
    hal_float_t delta;
};
struct __comp_state *__comp_first_inst=0, *__comp_last_inst=0;

static void _(struct __comp_state *__comp_inst, long period);
static int __comp_get_data_size(void);
#undef TRUE
#define TRUE (1)
#undef FALSE
#define FALSE (0)
#undef true
#define true (1)
#undef false
#define false (0)

static int export(char *prefix, long extra_arg) {
    char buf[HAL_NAME_LEN + 1];
    int r = 0;
    int sz = sizeof(struct __comp_state) + __comp_get_data_size();
    struct __comp_state *inst = hal_malloc(sz);
    memset(inst, 0, sz);
    r = hal_pin_bit_newf(HAL_OUT, &(inst->output), comp_id,
        "%s.output", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_IN, &(inst->x_target), comp_id,
        "%s.x-target", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_IN, &(inst->y_target), comp_id,
        "%s.y-target", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_IN, &(inst->x_current), comp_id,
        "%s.x-current", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_IN, &(inst->y_current), comp_id,
        "%s.y-current", prefix);
    if(r != 0) return r;
    r = hal_param_float_newf(HAL_RO, &(inst->delta), comp_id,
        "%s.delta", prefix);
    inst->delta = 0.01;
    if(r != 0) return r;
    rtapi_snprintf(buf, sizeof(buf), "%s", prefix);
    r = hal_export_funct(buf, (void(*)(void *inst, long))_, inst, 1, 0, comp_id);
    if(r != 0) return r;
    if(__comp_last_inst) __comp_last_inst->_next = inst;
    __comp_last_inst = inst;
    if(!__comp_first_inst) __comp_first_inst = inst;
    return 0;
}
static int default_count=1, count=0;
RTAPI_MP_INT(count, "number of syncoutputv1");
char *names = ""; // comma separated names
RTAPI_MP_STRING(names, "names of syncoutputv1");
int rtapi_app_main(void) {
    int r = 0;
    int i;
    comp_id = hal_init("syncoutputv1");
    if(comp_id < 0) return comp_id;
    if(count && names[0]) {
        rtapi_print_msg(RTAPI_MSG_ERR,"count= and names= are mutually exclusive\n");
        return -EINVAL;
    }
    if(!count && !names[0]) count = default_count;
    if(count) {
        for(i=0; i<count; i++) {
            char buf[HAL_NAME_LEN + 1];
            rtapi_snprintf(buf, sizeof(buf), "syncoutputv1.%d", i);
            r = export(buf, i);
            if(r != 0) break;
       }
    } else {
        int j,idx;
        char *ptr;
        char buf[HAL_NAME_LEN+1];
        ptr = names;
        idx = 0;
        for (i=0,j=0; i <= strlen(names); i++) {
            buf[j] = *(ptr+i);
            if ( (*(ptr+i) == ',') || (*(ptr+i) == 0) ) {
                buf[j] = 0;
                r = export(buf, idx);
                if (*(ptr+i+1) == 0) {break;}
                idx++;
                if(r != 0) {break;}
                j=0;
            } else {
                j++;
            }
        }
    }
    if(r) {
        hal_exit(comp_id);
    } else {
        hal_ready(comp_id);
    }
    return r;
}

void rtapi_app_exit(void) {
    hal_exit(comp_id);
}

#undef FUNCTION
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#undef EXTRA_SETUP
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#undef EXTRA_CLEANUP
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#undef fperiod
#define fperiod (period * 1e-9)
#undef output
#define output (*__comp_inst->output)
#undef x_target
#define x_target (0+*__comp_inst->x_target)
#undef y_target
#define y_target (0+*__comp_inst->y_target)
#undef x_current
#define x_current (0+*__comp_inst->x_current)
#undef y_current
#define y_current (0+*__comp_inst->y_current)
#undef delta
#define delta (__comp_inst->delta)


#line 15 "syncoutputv1.comp"
#include <rtapi_math.h>
FUNCTION(_){
    float temp= 0;
    temp += pow(x_current - x_target,2) ; 
    temp += pow(y_current - y_target,2) ; 
    temp = sqrt(temp) ; 
    output = (temp < delta) ? 1 : 0;
}



static int __comp_get_data_size(void) { return 0; }
